context:
  colors: [
      {
          name: "angry-blue",
          hex: "#2cf4f6"
      },
      {
          name: "angry-yellow",
          hex: "#f3f935"
      },
      {
          name: "baby-blue",
          hex: "#c9fbff"
      },
      {
          name: "blue-green",
          hex: "#12d2a0"
      },
      {
          name: "blue-sky",
          hex: "#d0e1f9"
      },
      {
          name: "blue",
          hex: "#5bb4f9"
      },
      {
          name: "bright-yellow",
          hex: "#fcf05b"
      },
      {
          name: "childs-blue",
          hex: "#2cd6f6"
      },
      {
          name: "cream-yellow",
          hex: "#fff5b3"
      },
      {
          name: "cyan",
          hex: "#69d5d7"
      },
      {
          name: "dark-pink",
          hex: "#e172c0"
      },
      {
          name: "dirty-yellow",
          hex: "#dbde0e"
      },
      {
          name: "dust-green",
          hex: "#b3c74b"
      },
      {
          name: "dusty-purple",
          hex: "#cec3d6"
      },
      {
          name: "dusty-yellow",
          hex: "#e1dfba"
      },
      {
          name: "egg-yolk",
          hex: "#ffd717"
      },
      {
          name: "eggshell",
          hex: "#b6d5e1"
      },
      {
          name: "forest-green",
          hex: "#0ec335"
      },
      {
          name: "gold",
          hex: "#edd256"
      },
      {
          name: "grey-blue",
          hex: "#e7f4f6"
      },
      {
          name: "grey-brown",
          hex: "#cfc4a2"
      },
      {
          name: "leaf",
          hex: "#96c99c"
      },
      {
          name: "light-brown",
          hex: "#f4e1c8"
      },
      {
          name: "light-pink",
          hex: "#ecc9c2"
      },
      {
          name: "light-purple",
          hex: "#ce9cef"
      },
      {
          name: "lime",
          hex: "#b9ed69"
      },
      {
          name: "messy-purple",
          hex: "#a1abc2"
      },
      {
          name: "mint-green",
          hex: "#4bc87f"
      },
      {
          name: "mud-green",
          hex: "#bcd096"
      },
      {
          name: "mud-yellow",
          hex: "#c2af2d"
      },
      {
          name: "ocean-blue",
          hex: "#98f5da"
      },
      {
          name: "ocean-mint",
          hex: "#07c3b3"
      },
      {
          name: "orange",
          hex: "#ff9a00"
      },
      {
          name: "peach",
          hex: "#ffb072"
      },
      {
          name: "pink",
          hex: "#f6a2d2"
      },
      {
          name: "raspberry",
          hex: "#ff7b90"
      },
      {
          name: "salmon",
          hex: "#f87a7a"
      },
      {
          name: "sand-storm",
          hex: "#e9e0a4"
      },
      {
          name: "sand",
          hex: "#ffd281"
      },
      {
          name: "silent-green",
          hex: "#ceffd6"
      },
      {
          name: "sky-purple",
          hex: "#f4f5ff"
      },
      {
          name: "soft-pink",
          hex: "#f5cdea"
      },
      {
          name: "strawberry",
          hex: "#fd6060"
      },
      {
          name: "summer-pink",
          hex: "#f1a5b3"
      },
      {
          name: "tangerine",
          hex: "#ffac3c"
      },
      {
          name: "teal-blue",
          hex: "#87c3bd"
      },
      {
          name: "teal-green",
          hex: "#0ad6cb"
      },
      {
          name: "tru-pink",
          hex: "#ff89b3"
      },
      {
          name: "velvet",
          hex: "#8f82c1"
      },
      {
          name: "winter-blue",
          hex: "#87c3d6"
      },
  ]
title: "Theme colors"
label: "Theme color"
status: wip
